site_name: In-Situ XRD Plotter


theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
            options:
              show_source: true
              show_root_heading: true
              show_submodules: false
            paths: [src]
  - gen-files:
      scripts:
        - docs/gen_api_v2.py
  - awesome-pages
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - index.md
  - User Manual:
      - Overview: user_manual/overview.md

      - Getting Started:
         - Installation: user_manual/getting_started/installation.md
         - Configuration Creation: user_manual/getting_started/config_creation.md
         - Start New Test: user_manual/getting_started/create_new_test.md



  - API: api/index.md
