site_name: In-Situ XRD Plotter

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
  - gen-files:
      scripts:
        - docs/gen_api.py
  - awesome-pages


nav:
  - Home: index.md
  - API: api/index.md

